###
GET  http://localhost:3001/api/notes/



###
POST http://localhost:3001/api/notes/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYiAzIiwiaWQiOjMsImlhdCI6MTcyNjcyOTc2MX0.04MRuCvpTLNdFp6F-bkayUhxfc5mlnjJJO1huHAQpqs

{
    "content": "new note 3",
    "important":true

}

###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    
    "important": true
}

###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "nab 4",
    "name": "nabina 4",
    "disabled":true
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "nab 1",
    "password": "secret"
   
}
###
PUT http://localhost:3001/api/users/nab 2
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYiAxIiwiaWQiOjEsImlhdCI6MTcyNjc0MzgwMn0.RZcHFOt47-64mlomIfSKEWdpn4qn53PA0MVYQG_N4PE

{
    
    "disabled": true
}
