###
GET  http://localhost:3001/api/notes/



###
POST http://localhost:3001/api/notes/
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYiAxIiwiaWQiOjIsImlhdCI6MTcyNTcxNjc0OH0.AF6L1NSLOsbEzIiQNqClDpfVV2MwR_cHVmejz1A8yzE

{
    "content": "checking allownull from note model",
    "important":true

}

###
PUT http://localhost:3001/api/notes/2
content-type: application/json

{
    
    "important": true
}

###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "nab 1",
    "name": "nabina 1"
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "nab 1",
    "password": "secret"
   
}
