DELETE http://localhost:3001/api/notes/2
###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hYmkxNCIsImlkIjoiNjY2OTMyYjM0OGJlNzMxZGNlZTA0MzBmIiwiaWF0IjoxNzE4MTcwMzU0LCJleHAiOjE3MTgxNzAzODR9.KPZLJvK672lf1VWL16JnMRWp782poOoUfwhpQVeFtr8

{
    "content": "hi nabina",
    "important": false,
    "userId":"666932b348be731dcee0430f"
}
###
PUT  http://localhost:3001/api/notes/664ed0244e1c573df5fe8708
content-type: application/json

{
    "content": "sample notes",
    "important": false
}
###
POST http://localhost:3001/api/users/
content-type: application/json

{
    "name":"Nabina Mangrati",
    "username": "nabi14",
    "password":"nabina123"
}
###
POST http://localhost:3001/api/login/
content-type: application/json

{
    
    "username": "nabi14",
    "password":"nabina123"
}